// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scm.Data;

namespace scm.Migrations
{
    [DbContext(typeof(ScmContext))]
    [Migration("20200324163855_new02")]
    partial class new02
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Scm.Domain.Estudiantes", b =>
                {
                    b.Property<int>("IdEstudiantes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apellido1")
                        .IsRequired()
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.Property<string>("Apellido2")
                        .IsRequired()
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.Property<int>("Edad")
                        .HasColumnType("int")
                        .HasMaxLength(200);

                    b.Property<string>("Genero")
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.HasKey("IdEstudiantes");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("Scm.Domain.Horarios", b =>
                {
                    b.Property<string>("Clave")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Dias")
                        .IsRequired()
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.Property<string>("Materia")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Rfc")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Salon")
                        .IsRequired()
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.HasKey("Clave");

                    b.HasIndex("Materia");

                    b.HasIndex("Rfc");

                    b.ToTable("horarios");
                });

            modelBuilder.Entity("Scm.Domain.Maestros", b =>
                {
                    b.Property<string>("Rfc")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.HasKey("Rfc");

                    b.ToTable("maestros");
                });

            modelBuilder.Entity("Scm.Domain.Materias", b =>
                {
                    b.Property<string>("Materia")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Materia");

                    b.ToTable("materias");
                });

            modelBuilder.Entity("Scm.Domain.User", b =>
                {
                    b.Property<string>("email")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.Property<string>("token")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("email");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Scm.Domain.Horarios", b =>
                {
                    b.HasOne("Scm.Domain.Materias", "Materias")
                        .WithMany()
                        .HasForeignKey("Materia");

                    b.HasOne("Scm.Domain.Maestros", "Maestros")
                        .WithMany()
                        .HasForeignKey("Rfc");
                });
#pragma warning restore 612, 618
        }
    }
}
